### PR TITLE
Added support for mapping request fields to partition and range keys

### LINKED ISSUE #64: Ability to map fields in the request to partition/range keys for dynamo
Users should be able to set up their table partition/hashKeys to accept fields from the income request.

For example,

If I were to set up a user table with partition scheme of "{name}:{email}", mindless should be able to map the `name` and `email` fields from a request to the partition key.

The following request
```
{
    "name": "Evan",
    "email": "evan@gmail.com"
}

```

would then use "Evan:evan@gmail.com" as the partition key value for dynamo access

### PR DESCRIPTION
**Pull request by moraneva**
closes #64

### CODE REVIEW

**Comment by moraneva** [comment]
@zRosenthal please feel free to clean this up if you want, if not i will hopefully do it within the next few days

**Comment by zRosenthal** [comment]
Also according to lodash docs 

> [_.omit] is considerably slower than _.pick.

so I think we could switch to `pick` or roll our own and not use lodash

**Comment by moraneva** [comment]
@zRosenthal nice coveralls

**Comment by moraneva** [comment]
@zRosenthal yeah, probably don't even need lodash for now since this would be the only use case. I think we can just delete fields instead of doing this

**Pull request closed without merging**
